### ISSUE TITLE
DynamoDBClient region issue

### ISSUE THREAD

**Issue by ca-gopalk** [tjanczuk/letsgo#10]
In the file, letsgo\packages\db\src\index.ts 

Current: 

![image](https://github.com/47chapters/letsgo/assets/121535527/0f91c0f0-c373-496e-9fa9-92f899e21383)

Expected: 

![image](https://github.com/47chapters/letsgo/assets/121535527/f0cb73c0-9cd8-4632-b1e9-f81ccf7d902a)

In line number 122, instead of DefaultRegion, we need to set region

**Comment by tjanczuk** [comment]
Good catch, thanks for reporting! Fix will go out in the next release in a few days.

**Comment by tjanczuk** [comment]
Fixed in 50d98083ac46bd4fa496ad4f5e3156f10185be1d released as v2.0.0
