### ISSUE TITLE
AWS App Runner issue due to mismatching arch when building docker image in Apple silicon

### ISSUE THREAD

**Issue by mauricioschneider** [tjanczuk/letsgo#14]
When running `yarn ops deploy -a all`, the App Runner service for the API fails with the following logs:

## App Runner event logs
```
 [AppRunner] Deployment with ID : x started. Triggering event : SERVICE_CREATE
 [AppRunner] Deployment Artifact: [Repo Type: ECR], [Image URL: x.dkr.ecr.us-west-2.amazonaws.com/letsgo-main-api], [Image Tag: 60f617e3ad194880]
 [AppRunner] Pulling image x.dkr.ecr.us-west-2.amazonaws.com/letsgo-main-api from ECR repository.
 [AppRunner] Successfully pulled your application image from ECR.
 [AppRunner] Provisioning instances and deploying image for publicly accessible service.
 [AppRunner] Performing health check on protocol `HTTP` [Path: '/v1/health'], [Port: '8080'].
 [AppRunner] Your application stopped or failed to start. See logs for more information.  Container exit code: 1
 [AppRunner] Deployment with ID : x failed.
```

## Application logs
```
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

I'm running letsgo on an Macbook Pro M3 Max, and according to this [SO post](https://stackoverflow.com/a/73400257), it's related to mismatching architecture used to build the docker image vs the one where the docker image will run. Here's a more [in-depth explanation.](https://stackoverflow.com/a/69636473)

**Comment by mauricioschneider** [comment]
Besides changing the `FROM` in the Dockerfile, it's possible to use a [environment variable](https://stackoverflow.com/a/66900911), `export DOCKER_DEFAULT_PLATFORM=linux/amd64`.

**Comment by mauricioschneider** [comment]
After changing the first line of `api/Dockerfile` to `FROM --platform=linux/amd64 node:18-alpine AS base`, the deployment of the image to App Runner is successful.

**Comment by mauricioschneider** [comment]
The line above should be used in all `Dockerfile` copies in api, web, and worker.

**Comment by tjanczuk** [comment]
Good catch, fix coming.
